---
region: 'eu-west-1'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

parent_domain_name: "infrablocks.click"
delegated_domain_name: "%{hiera('deployment_identifier')}.%{hiera('parent_domain_name')}"
