---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  parent_domain_name: "%{hiera('parent_domain_name')}"
  delegated_domain_name: "%{hiera('delegated_domain_name')}"
